spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/permissiondb?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password:
  mvc:
    view:
      suffix: .jsp
      prefix: /WEB-INF/jsp/
  thymeleaf:
    cache: false
    enabled: false

mybatis:
  typeAliasesPackage: com.qzeng2490.permisson.model
  mapperLocations: classpath:mapper/*.xml
